import { useMemo, useState } from 'react'
import {
  ResizableDialog,
  ResizableDialogContent,
  ResizableDialogDescription,
  ResizableDialogHeader,
  ResizableDialogTitle,
} from '@/components/ui/resizable-dialog'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import {
  TEST_FAMILIES,
  getTestsByGroup,
  type TestDefinition,
  type TestGroupId,
} from '@/config/testRegistry'
import { normalizeTestId } from '@/services/plotResult/common/normalize'
import { getAutoGeneratedPlotLabelsForTest } from '@/services/plotResultService'
import { cn } from '@/lib/utils'

interface StatisticalTestsGuideDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onOpenSampleDatasets?: (search?: string) => void
  onRunTest?: (testId: string) => void
  groupIds?: TestGroupId[]
  title?: string
  description?: string
}

const DEFAULT_GROUPS: TestGroupId[] = [
  'hypothesis_testing',
  'pharmacology',
  'regression_correlation',
  'categorical',
  'distribution_descriptive',
  'survival',
  'mediation_moderation',
]

const formatFieldLabel = (field: TestDefinition['requiredDataFields'][number]) => {
  const base = field.label
  const requirement = field.multiple ? ` (≥${field.minColumns ?? 2})` : ''
  const optional = field.required === false ? ' (optional)' : ''
  return `${base}${requirement}${optional}`
}

const formatParamLabel = (param: TestDefinition['parameters'][number]) => {
  const defaultValue =
    param.default === null || param.default === undefined ? '—' : String(param.default)
  return `${param.label} (default: ${defaultValue})`
}

const MANIFEST_SEARCH_OVERRIDES: Record<string, string> = {
  mann_whitney: 'mann_whitney',
  chi_square_gof: 'chi_squared_gof',
  descriptive_stats: 'descriptive_statistics',
  normality_all: 'normality_tests',
}

const getSampleDatasetSearch = (testId: string) => {
  if (testId in MANIFEST_SEARCH_OVERRIDES) return MANIFEST_SEARCH_OVERRIDES[testId]
  return normalizeTestId(testId)
}

const getFamilyLabel = (family: string) => {
  const info = TEST_FAMILIES[family as keyof typeof TEST_FAMILIES]
  if (info?.displayName) return info.displayName
  return family
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

export function StatisticalTestsGuideDialog({
  open,
  onOpenChange,
  onOpenSampleDatasets,
  onRunTest,
  groupIds = DEFAULT_GROUPS,
  title = 'Statistical Tests Guide',
  description = 'Quick reference for statistical tests. See required inputs, parameters, and typical plots before you run a test.',
}: StatisticalTestsGuideDialogProps) {
  const [query, setQuery] = useState('')

  const tests = useMemo(() => {
    const merged = groupIds.flatMap(groupId => getTestsByGroup(groupId))
    const seen = new Set<string>()
    return merged.filter(test => {
      if (seen.has(test.id)) return false
      seen.add(test.id)
      return true
    })
  }, [groupIds])
  const filteredTests = useMemo(() => {
    const needle = query.trim().toLowerCase()
    if (!needle) return tests
    return tests.filter(test => {
      const haystack = [
        test.displayName,
        test.id,
        test.description ?? '',
        test.family,
      ]
        .join(' ')
        .toLowerCase()
      return haystack.includes(needle)
    })
  }, [query, tests])

  const groupedTests = useMemo(() => {
    const map = new Map<string, TestDefinition[]>()
    const familyOrder: string[] = []
    for (const test of filteredTests) {
      const family = test.family ?? 'other'
      if (!map.has(family)) {
        map.set(family, [])
        familyOrder.push(family)
      }
      map.get(family)!.push(test)
    }
    return familyOrder.map(family => [family, map.get(family)!] as const)
  }, [filteredTests])

  return (
    <ResizableDialog
      open={open}
      onOpenChange={onOpenChange}
      defaultWidth={1050}
      defaultHeight={780}
      minWidth={840}
      minHeight={640}
      persistKey="statistical-tests-guide"
    >
        <ResizableDialogContent className="flex flex-col p-0">
          <ResizableDialogHeader className="px-6 pt-6 pb-4 border-b">
          <ResizableDialogTitle className="text-xl">{title}</ResizableDialogTitle>
          <ResizableDialogDescription>
            {description}
          </ResizableDialogDescription>
          <div className="mt-4 grid grid-cols-[minmax(0,1fr)_auto] items-center gap-3">
            <Input
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Search tests (e.g., t-test, ANOVA, regression)…"
            />
            <div className="text-xs text-muted-foreground">
              {filteredTests.length} test{filteredTests.length === 1 ? '' : 's'}
            </div>
          </div>
        </ResizableDialogHeader>

        <div className="flex-1 min-h-0">
          <ScrollArea className="h-full">
            <div className="p-6 space-y-6">
              {groupedTests.length === 0 && (
                <div className="rounded-lg border border-dashed border-border/60 p-6 text-sm text-muted-foreground">
                  No tests match your search.
                </div>
              )}

              {groupedTests.map(([family, familyTests]) => (
                <section key={family} className="space-y-4">
                  <div className="flex items-center gap-2">
                    <h3 className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                      {getFamilyLabel(family)}
                    </h3>
                    <span className="text-xs text-muted-foreground">
                      {familyTests.length} test{familyTests.length === 1 ? '' : 's'}
                    </span>
                  </div>

                  <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
                    {familyTests.map(test => {
                      const autoPlotLabels = getAutoGeneratedPlotLabelsForTest(test.id)
                      const sampleSearch = getSampleDatasetSearch(test.id)
                      const showTypicalPlots =
                        test.family !== 'mediation' && test.family !== 'moderation'

                      return (
                        <Card key={test.id} className="border-border/60">
                          <CardHeader className="space-y-2">
                            <div className="flex items-start justify-between gap-3">
                              <div className="space-y-1">
                                <CardTitle className="text-base">{test.displayName}</CardTitle>
                                {test.description && (
                                  <CardDescription className="text-xs">
                                    {test.description}
                                  </CardDescription>
                                )}
                              </div>
                              <Badge variant="secondary" className="uppercase text-[10px]">
                                {getFamilyLabel(test.family)}
                              </Badge>
                            </div>
                          </CardHeader>
                          <CardContent className="space-y-4 text-sm">
                            <div className="space-y-1">
                              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                                Inputs
                              </p>
                              {test.requiredDataFields.length === 0 ? (
                                <p className="text-xs text-muted-foreground">Columns selected in column picker (DV + predictors)</p>
                              ) : (
                                <ul className="text-xs text-muted-foreground space-y-1">
                                  {test.requiredDataFields.map(field => (
                                    <li key={field.name}>{formatFieldLabel(field)}</li>
                                  ))}
                                </ul>
                              )}
                            </div>

                            <div className="space-y-1">
                              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                                Parameters
                              </p>
                              {test.parameters.length === 0 ? (
                                <p className="text-xs text-muted-foreground">None</p>
                              ) : (
                                <ul className="text-xs text-muted-foreground space-y-1">
                                  {test.parameters.map(param => (
                                    <li key={param.name}>{formatParamLabel(param)}</li>
                                  ))}
                                </ul>
                              )}
                            </div>

                            {showTypicalPlots && (
                              <div className="space-y-1">
                                <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                                  Typical Plots
                                </p>
                                <div className="text-xs text-muted-foreground space-y-1">
                                  <div>
                                    Auto-generated:{' '}
                                    <span className={cn(autoPlotLabels.length === 0 && 'text-muted-foreground/70')}>
                                      {autoPlotLabels.length > 0
                                        ? autoPlotLabels.join(', ')
                                        : 'None'}
                                    </span>
                                  </div>
                                </div>
                              </div>
                            )}

                            <div className="flex items-center gap-2 pt-1">
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => {
                                  onOpenSampleDatasets?.(sampleSearch)
                                  onOpenChange(false)
                                }}
                              >
                                View Example Data
                              </Button>
                              <Button
                                size="sm"
                                onClick={() => {
                                  onRunTest?.(test.id)
                                  onOpenChange(false)
                                }}
                              >
                                Run This Test
                              </Button>
                            </div>
                          </CardContent>
                        </Card>
                      )
                    })}
                  </div>
                </section>
              ))}
            </div>
          </ScrollArea>
        </div>
      </ResizableDialogContent>
    </ResizableDialog>
  )
}

export default StatisticalTestsGuideDialog
